# Service Name
spring.application.name=event-service

# Server Port
server.port=8082

# Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/EventServiceDB
spring.datasource.username=postgres
spring.datasource.password=

# JPA Config
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka Client Config
eureka.client.enabled=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
